"""添加geocoded状态

Revision ID: d39d4f6d8c49
Revises: 65c00e8f3887
Create Date: 2025-11-04 00:10:13.719186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39d4f6d8c49'
down_revision = '65c00e8f3887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geocoded_status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('geocoded_status')

    # ### end Alembic commands ###
